# Generated by Django 5.2.8 on 2025-11-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='member',
            new_name='members',
        ),
    ]
